### ISSUE TITLE
Bug- Adding a new meetup without filling time throws an error

### ISSUE THREAD

**Issue by poojithansl** [anitab-org/portal#286] opened 2017-12-14 09:34 UTC
Time field must be required too. 
@tapasweni-pathak Currently there's only starting time, but no end time for an event/meetup.
How about adding a new field for end time to the model?

**Comment by aashutoshrathi** [comment] 2018-03-17 10:16
Is this one fixed? Anyone working on it?

**Comment by abhi20161997** [comment] 2018-11-12 15:40
@Tlazypanda please comment and seek permission on issues before starting to work on them

**Comment by satya7289** [comment] 2020-06-13 08:04
Duplicate of the [issue](https://github.com/anitab-org/portal/issues/432).

**Closed by satya7289** 2020-06-13 08:04 UTC
Labels: Category: Coding, Status: Available, Type: Bug
