### ISSUE TITLE
Bug - github authentication still associated with private github account

### ISSUE THREAD

**Issue by Jaemu** [anitab-org/portal#344] opened 2018-03-07 03:44 UTC
## Description
As a user, I want to know that when I login with my github credentials to access the Systers portal I know that only Systers has access to my information.

*Update*
This issue is observable on portal.systers.org - 3P login is not available locally.

## Mocks
![screen shot 2018-03-06 at 7 39 04 pm](https://user-images.githubusercontent.com/2614791/37072452-8344730c-2176-11e8-9b8a-5584a3b8c9c1.png)

### Update [Required]
- [ ] Github authentication works as expected
- [ ] The user or organization requesting user information is clearly associated with Systers (name, branding, etc.)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[8] hours

**Comment by SETIADEEPANSHU** [comment] 2018-03-07 05:15
@Jaemu I have checked this , ana-balica was the one who created and is also the current owner of this app . the solution is either to transfer the ownership from her to systers or setup new oauth app using systers login credentials . The name of person or organisation who creates this oauth login is displayed there!

**Comment by sammy1997** [comment] 2018-03-08 16:18
@Jaemu What's the status of this issue ? What do we need to do ? And is anyone working on this now ?

**Comment by satya7289** [comment] 2020-06-13 08:12
Duplicate of this [issue](https://github.com/anitab-org/portal/issues/533)

**Closed by satya7289** 2020-06-13 08:12 UTC
Labels: Type: Bug
