### ISSUE TITLE
Pillow version

### ISSUE THREAD

**Issue by bv-hcr** [anitab-org/portal#465] opened 2019-10-17 08:13 UTC
```
- Pillow==4.3.0
+ Pillow==6.2.0
```
https://pillow.readthedocs.io/en/latest/installation.html

**Comment by bv-hcr** [comment] 2019-10-17 08:15
stderr~
```
  Traceback (most recent call last):
    File "/tmp/pip-install-irr8k8_3/Pillow/setup.py", line 787, in <module>
      zip_safe=not (debug_build() or PLATFORM_MINGW), )
    File "/root/django_test/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Python-3.7.5/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Python-3.7.5/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/Python-3.7.5/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/root/django_test/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/local/Python-3.7.5/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Python-3.7.5/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/Python-3.7.5/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Python-3.7.5/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Python-3.7.5/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/Python-3.7.5/lib/python3.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/tmp/pip-install-irr8k8_3/Pillow/setup.py", line 577, in build_extensions
      raise RequiredDependencyException(f)
  __main__.RequiredDependencyException: jpeg

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-irr8k8_3/Pillow/setup.py", line 799, in <module>
      raise RequiredDependencyException(msg)
  __main__.RequiredDependencyException:

  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.

  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html


  ----------------------------------------
  ERROR: Failed building wheel for Pillow
  Running setup.py clean for Pillow
Failed to build Pillow
```

**Comment by sammy1997** [comment] 2020-03-16 17:35
Couldn't reproduce this error. I think we will open a dependency upload issue and update all dependencies than doing this separately for each dependency. Closing the issue for now
![Pillow version](https://user-images.githubusercontent.com/24635701/76784886-7adc2280-67da-11ea-9b1f-8347c86d323e.png)

**Closed** 2020-03-16 17:35 UTC
